source "https://rubygems.org"

ruby "3.1.2"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"

gem "sprockets-rails"

gem "sqlite3", "~> 1.4"

gem "puma", ">= 5.0"

gem "importmap-rails"

gem "turbo-rails"

gem "stimulus-rails"


gem "jbuilder"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

gem "bootsnap", require: false


group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem 'capybara'
  gem 'database_cleaner'
  gem 'bootstrap-sass', '~> 3.3.7'

  gem 'sassc-rails'

end

group :development do
  gem "web-console"

  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end

